name: function

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    env:
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: $WORKLOAD_IDENTITY_PROVIDER
          service_account: $SERVICE_ACCOUNT
          audience: 'https://github.com/ntk01'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'    
      - name: Deploy
        run: gcloud functions deploy scheduled_tweet --region=asia-northeast1 --runtime=python311 --trigger-topic=tweet --entry-point=main
