name: function

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/172132580704/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions-deploy@notification-390207.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
      - name: Deploy
        run: gcloud functions deploy scheduled_tweet --region=asia-northeast1 --runtime=python311 --trigger-topic=tweet --entry-point=main
